# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#admin = User.create(email: 'admin@uoftironsports.ca',
                    #password: ENV['ADMIN_PASS'], password_confirmation: ENV['ADMIN_PASS'],
                    #first_name: 'Amanda', last_name: 'Santos',
                    #gender: 'F', registration_number: 0)
#admin.is_admin = true
#admin.save!

meet1 = Meet.create(title: 'Octobr 5th 2013 Classic 3-Lift Competition')
meet1.meet_results = [
  MeetResult.create(
    lifter:             'Walter Cariazo',
    weight:             94.95,
    gender:             'M',
    squat1:             170,
    squat1_success:     true,
    squat2:             285,
    squat2_success:     true,
    squat3:             200,
    squat3_success:     true,
    bench1:             130,
    bench1_success:     false,
    bench2:             155,
    bench2_success:     true,
    bench3:             165,
    bench3_success:     false,
    deadlift1:          240,
    deadlift1_success:  true,
    deadlift2:          255,
    deadlift2_success:  true,
    deadlift3:          273,
    deadlift3_success:  true,
  ),
  MeetResult.create(
    lifter: 'Mark Tatangelo',
    weight: 94.77,
    gender: 'M',
    squat1:           195,
    squat1_success:   true,
    squat2:           205,
    squat2_success:   true,
    squat3:           215,
    squat3_success:   true,
    bench1:           110,
    bench1_success:   true,
    bench2:           125,
    bench2_success:   true,
    bench3:           137,
    bench3_success:   true,
    deadlift1:        215,
    deadlift1_success:true,
    deadlift2:        240,
    deadlift2_success:true,
    deadlift3:        261,
    deadlift3_success:true,
  ),
  MeetResult.create(
    lifter: 'Adam Crockford',
    weight: 102,
    gender: 'M',
    squat1:           165,
    squat1_success:   true,
    squat2:           175,
    squat2_success:   true,
    squat3:           185,
    squat3_success:   true,
    bench1:           115,
    bench1_success:   true,
    bench2:           121,
    bench2_success:   true,
    bench3:           131,
    bench3_success:   true,
    deadlift1:        239,
    deadlift1_success:true,
    deadlift2:        250,
    deadlift2_success:true,
    deadlift3:        273,
    deadlift3_success:false,
  ),
  MeetResult.create(
    lifter: 'Andrey Vul',
    weight: 111.27,
    gender: 'M',
    squat1:           215,
    squat1_success:   true,
    squat2:           225,
    squat2_success:   true,
    squat3:           235,
    squat3_success:   true,
    bench1:           113,
    bench1_success:   false,
    bench2:           113,
    bench2_success:   true,
    bench3:           123,
    bench3_success:   false,
    deadlift1:        217,
    deadlift1_success:true,
    deadlift2:        225,
    deadlift2_success:true,
    deadlift3:        233,
    deadlift3_success:true,
  ),
  MeetResult.create(
    lifter: 'George Ceko',
    weight: 90.90,
    gender: 'M',
    squat1:           135,
    squat1_success:   true,
    squat2:           145,
    squat2_success:   true,
    squat3:           150,
    squat3_success:   true,
    bench1:           105,
    bench1_success:   true,
    bench2:           110,
    bench2_success:   true,
    bench3:           115,
    bench3_success:   true,
    deadlift1:        185,
    deadlift1_success:true,
    deadlift2:        195,
    deadlift2_success:true,
    deadlift3:        205,
    deadlift3_success:true,
  ),
  MeetResult.create(
    lifter: 'Christopher Juman',
    weight: 89.45,
    gender: 'M',
    squat1:           143,
    squat1_success:   false,
    squat2:           147,
    squat2_success:   false,
    squat3:           151,
    squat3_success:   true,
    bench1:           93,
    bench1_success:   true,
    bench2:           103,
    bench2_success:   true,
    bench3:           107,
    bench3_success:   true,
    deadlift1:        183,
    deadlift1_success:true,
    deadlift2:        200,
    deadlift2_success:true,
    deadlift3:        208,
    deadlift3_success:true,
  ),
  MeetResult.create(
    lifter: 'Jeremy Louie',
    weight: 84.86,
    gender: 'M',
    squat1:           125,
    squat1_success:   true,
    squat2:           145,
    squat2_success:   true,
    squat3:           149,
    squat3_success:   false,
    bench1:           105,
    bench1_success:   false,
    bench2:           107,
    bench2_success:   true,
    bench3:           111,
    bench3_success:   false,
    deadlift1:        181,
    deadlift1_success:true,
    deadlift2:        191,
    deadlift2_success:false,
    deadlift3:        200,
    deadlift3_success:true,
  ),
  MeetResult.create(
    lifter: 'Nicolo Marchisao',
    weight: 68.45,
    gender: 'M',
    squat1:           115,
    squat1_success:   true,
    squat2:           120,
    squat2_success:   true,
    squat3:           125,
    squat3_success:   false,
    bench1:           70,
    bench1_success:   true,
    bench2:           75,
    bench2_success:   true,
    bench3:           80,
    bench3_success:   false,
    deadlift1:        140,
    deadlift1_success:true,
    deadlift2:        142,
    deadlift2_success:true,
    deadlift3:        145,
    deadlift3_success:true,
  ),
  MeetResult.create(
    lifter: 'Will Kingsford',
    weight: 102.72,
    gender: 'M',
    squat1:           140,
    squat1_success:   true,
    squat2:           150,
    squat2_success:   true,
    squat3:           160,
    squat3_success:   true,
    bench1:           85,
    bench1_success:   true,
    bench2:           93,
    bench2_success:   false,
    bench3:           100,
    bench3_success:   false,
    deadlift1:        170,
    deadlift1_success:true,
    deadlift2:        190,
    deadlift2_success:false,
    deadlift3:        190,
    deadlift3_success:false,
  ),
  MeetResult.create(
    lifter: 'Lucy Trojanowski',
    weight: 77.6,
    gender: 'F',
    squat1:           69,
    squat1_success:   true,
    squat2:           79,
    squat2_success:   true,
    squat3:           89,
    squat3_success:   true,
    bench1:           49,
    bench1_success:   true,
    bench2:           57,
    bench2_success:   false,
    bench3:           57,
    bench3_success:   true,
    deadlift1:        91,
    deadlift1_success:true,
    deadlift2:        105,
    deadlift2_success:true,
    deadlift3:        113,
    deadlift3_success:true,
  ),
  MeetResult.create(
    lifter: 'Jordan Louie',
    weight: 67,
    gender: 'M',
    squat1:           75,
    squat1_success:   true,
    squat2:           95,
    squat2_success:   false,
    squat3:           105,
    squat3_success:   false,
    bench1:           75,
    bench1_success:   false,
    bench2:           75,
    bench2_success:   false,
    bench3:           75,
    bench3_success:   false,
    deadlift1:        135,
    deadlift1_success:true,
    deadlift2:        143,
    deadlift2_success:true,
    deadlift3:        145,
    deadlift3_success:true,
  ),
  MeetResult.create(
    lifter: 'Phillip Chan',
    weight: 68.81,
    gender: 'M',
    squat1:           127,
    squat1_success:   true,
    squat2:           139,
    squat2_success:   false,
    squat3:           139,
    squat3_success:   false,
    bench1:           81,
    bench1_success:   true,
    bench2:           85,
    bench2_success:   true,
    bench3:           89,
    bench3_success:   false,
    deadlift1:        180,
    deadlift1_success:false,
    deadlift2:        185,
    deadlift2_success:false,
    deadlift3:        185,
    deadlift3_success:false,
  )
]
meet1.save!
